# Double: Length of time in which an IMU message cannot be received before it will be considered a fault
# Units: seconds
imu_timeout: 0.25

# Double: Length of time in which a GPS message cannot be received before it will be considered a fault
# Units: seconds
gnss_timeout: 0.25